name: money_record
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  d_chart: ^2.6.7
  d_info: ^0.2.2
  d_input: ^0.1.2
  d_method: ^0.2.4
  d_view: ^0.0.5
  flutter:
    sdk: flutter
  flutter_charts: ^0.5.2
  flutter_launcher_icons: ^0.13.1
  gap: ^3.0.1
  get: ^4.6.6
  google_mobile_ads: ^4.0.0
  http: ^1.2.0
  intl: ^0.17.0
  lottie: ^3.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icons"
  ios: true
  image_path: "asset/Hasil.png"

flutter:
  uses-material-design: true
  assets:
    - asset/
